# vim: ft=yaml.docker-compose
name: periphery
services:
  periphery:
    image: ghcr.io/rahulsalvi/komodo-periphery:latest
    labels:
      komodo.skip:
    restart: unless-stopped
    network_mode: host
    environment:
      PERIPHERY_SSL_ENABLED: false
      PERIPHERY_PASSKEYS_FILE: /etc/komodo/passkey
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
